# Generated by Django 2.2.3 on 2022-06-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(blank=True, choices=[('MENTOR', 'MENTOR'), ('MEMBER', 'MEMBER')], default=None, max_length=20, null=True),
        ),
    ]
