# Generated by Django 2.2.3 on 2022-06-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='expertis',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(blank=True, choices=[('MENTOR', 'Mentor'), ('MEMBER', 'Member')], default=None, max_length=20, null=True),
        ),
    ]
