# Generated by Django 2.2.3 on 2022-06-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220629_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(blank=True, choices=[('MENTOR', 'Mentor'), ('MEMBER', 'Member')], default=None, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='type',
        ),
    ]
