# Generated by Django 2.2.3 on 2022-06-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20220629_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('MentorP', 'MentorP'), ('MentorA', 'MentorA'), ('MemberA', 'MemberA'), ('MemberP', 'MemberP')], max_length=200, null=True),
        ),
    ]
